apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lightweight
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  labels:
    test: sdsds
  annotations:
    codefresh.io/app-group: test
spec:
  project: default
  source:
    path: lightweight
    repoURL: https://github.com/oleksandr-codefresh/argocd-example-apps
    targetRevision: personal-eks
  destination:
    name: in-cluster
    namespace: test-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
